### ISSUE TITLE
Compatibility with Dark Reader

### ISSUE THREAD

**Issue by tensorturtle** [ronv/jam#3]
I use Dark Reader [darkreader.org](https://darkreader.org/) a lot. It brings 'dark-mode' functionality to websites that don't actually have dark mode.

This theme works okay with it, except for one issue:

The background at the top is rendered as a lighter grey. When you scroll down, any background below the bottom of the initial screen is the correct dark grey.

I understand that you (the developer) might not know how Dark Reader works, but is there maybe some layer that could be causing this?

![dark](https://user-images.githubusercontent.com/75611662/148447035-f26d1d35-dbe5-4ce5-bfb7-737aa4bffff9.png)
![dark2](https://user-images.githubusercontent.com/75611662/148447045-d857174e-f439-49b0-a934-dd772d178746.png)

**Comment by ronv** [comment]
Hi, If need to implement dark mode on this theme I would suggest just change main section background color and text color and you will have it. 

Br, Ronalds

**Comment by tensorturtle** [comment]
Thank you very much for the replies!
