### ISSUE TITLE
LaTeX (KaTeX) support

### ISSUE THREAD

**Issue by tensorturtle** [ronv/jam#4]
Hello, I would love to see Latex (Katex) support for this theme.

Katex supposedly can render mathematical expressions into HTML, so no javascript on client side.

I found a guide, but I don't know how to incorporate it into this theme.

https://dzhg.dev/posts/2020/08/how-to-add-latex-support-in-hugo/

Could you try implementing it, or just point me to where in this theme I can apply the changes in this guide?

Thank you

**Comment by ronv** [comment]
Hi,

Maybe you could use MathJax and include it in source code? I'm not familiar with Latex. Here is tutorial: http://docs.mathjax.org/en/latest/web/configuration.html maybe it helps. I don't plan include it in this theme, you will have to add it manually.

Br, Ronalds
